version: '3.5'

services:
  api01: &api
    image: docker.io/kitsunesemcalda/rinha-backend:latest
    hostname: api01
    ports:
      - "8081:8081"
    privileged: true
    restart: on-failure
    environment:
      - PORT=8081
      - DB_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  
  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8082"
    restart: on-failure
    privileged: true
    environment:
      - PORT=8082
      - DB_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    restart: on-failure
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
  
  db:
    image: postgres:latest
    hostname: db
    restart: on-failure
    ports:
      - "5432:5432"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    privileged: true 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'admin', '-d', 'rinha']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits: 
          cpus: "0.3"
          memory: "330MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
