version: "3.5"
services:
  api1: &api
    image: docker.io/weversonlemos/rinha-v2:latest
    pull_policy: always
    hostname: api1
    container_name: api1-rb
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
    env_file:
      - ./config/.env
    environment:
      SERVER_PORT: 8080

    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "125MB"

    healthcheck:
      test: ["CMD", "true"]
      start_interval: 0.20s
      retries: 40
      interval: 4s
      timeout: 0.20s

  api2:
    <<: *api
    hostname: api2
    container_name: api2-rb
    environment:
      SERVER_PORT: 8081

  nginx:
    image: nginx:alpine
    container_name: nginx-rb
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

  postgres:
    image: postgres:16.2
    container_name: postgres-rb
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    network_mode: host

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf

    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "250MB"

    healthcheck:
      test: ["CMD", "true"]
      start_interval: 1s
      retries: 20
      interval: 4s
      timeout: 0.50s

volumes:
  postgres-data:
