version: "3.5"

services:
  api01: &api
    image: williammaia/rinha_backend_app:latest
    hostname: api01
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://api01:api01_pass@db:5432/dogfight?sslmode=disable&pool_min_conns=3
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      DATABASE_URL: postgres://api02:api02_pass@db:5432/dogfight?sslmode=disable&pool_min_conns=3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    command: postgres -S 8192
    environment:
      POSTGRES_DB: dogfight
      POSTGRES_USER: dogfight_user
      POSTGRES_PASSWORD: dogfight_pass
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: "260MB"

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  
  alpine:
    image: alpine
    tty: true