version: "3.5"
services:

  crdb:
    hostname: crdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --store=cockroach-rinha-data --cluster-name=rinha-backend-cluster --insecure
    ports:
      - "26257:26257"
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "300MB"

  api1: &app
    image: bourguignon/rinha-backend-2024-q1-java-micronaut:0.1
    hostname: api1
    restart: unless-stopped
    environment:
      - JDBC_URL=jdbc:postgresql://crdb:26257/postgres
    depends_on:
      - crdb
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "100MB"

  api2:
    <<: *app
    hostname: api2
    environment:
      - JDBC_URL=jdbc:postgresql://crdb:26257/postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha-backend