version: '3.9'

services:
  webapi1: &webapi1
    hostname: webapi1
    image: jonathanperis/rinha2-back-end-bora-dale:latest
    depends_on: 
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=postgres;Database=rinha;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=50;
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "165MB"
  
  webapi2:
    <<: *webapi1
    hostname: webapi2

  db:
    image: postgres
    volumes:
      - ./conf/rinha.dump.sql:/docker-entrypoint-initdb.d/rinha.dump.sql:ro
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1
      - webapi2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"